[package]
name = "manifest-update"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.4.11", features = ["derive"] }
package-lib = { path = "../package-lib" }
serde = { version = "^1.0.193", features = ["derive"] }
serde_json = "^1.0.108"
