[package]
name = "package-lib"
version = "1.2.0"
edition = "2024"

[dependencies]
jwalk = "^0.8.1"
serde = { version = "^1.0.218", features = ["derive"] }
serde_json = "^1.0.140"
unicode-bom = "^2.0.3"
