[package]
name = "package-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
jwalk = "^0.8.1"
serde = { version = "^1.0.193", features = ["derive"] }
serde_json = "^1.0.108"
unicode-bom = "^2.0.3"
